### ISSUE TITLE
errors occurred

### ISSUE THREAD

**Issue by XiaoruiChong** [danielk333/SORTS#37]
The following error occurred while running SORTS and SORTS_applications:
1.ModuleNotFoundError: No module named 'pyant.instances'
2.AttributeError: module 'pyant' has no attribute 'PlaneArrayInterp'
3.AttributeError: module 'pyant.statistics' has no attribute 'e3d_array_stage1'

hope to obtain the pyant library supporting SORTS

**Comment by danielk333** [comment]
Hello!

First off, it would be nice to if you could include the code where this error occurred and what system/environment it was running on when it happened (also the version of pyant would be useful).

Secondly, the ´sorts´ package is currently being refactored but due to very lite extra time on my part it is going quite slowly, so there are bound to be quite a lot of bugs and out of date examples and scripts right now. Those I will sort out (pun intended) over time.

Well, anyway, to me it looks like the API you are trying to call is from an old version of pyant, here you can check out the git of that package https://github.com/danielk333/pyant cant really say anything more without more context

Best, Daniel
